version: 1
disable_existing_loggers: false

formatters:
  json:
    (): uvicorn.logging.DefaultFormatter
    fmt: '{"level":"%(levelname)s", "timestamp":"%(asctime)s", "message":"%(message)s", "logger":"%(name)s"}'

handlers:
  default:
    formatter: json
    class: logging.StreamHandler

loggers:
  uvicorn:
    handlers:
      - default
