---

name: 01 Build and Push

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extracting metadata from a cloned repository
        id: get-cloned
        run: |-
          echo "::set-output name=SHA::$(git log -1 --format='%h')"

      - name: Set and sanitize image tag
        id: set-tag
        run: |
          IMAGE_TAG="${{ github.ref_name }}.${{ steps.get-cloned.outputs.SHA }}.${{ github.run_attempt }}"
          # replace slashes and invalid characters with hyphens
          IMAGE_TAG="$(echo "$IMAGE_TAG" | tr '/ ' '--' | tr -cs 'A-Za-z0-9_.-' '-' | sed 's/-$//')"
          # docker tags must start with alphanumeric character
          IMAGE_TAG="$(echo "$IMAGE_TAG" | sed 's/^[^A-Za-z0-9]*//')"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Check Nexus credentials
        id: creds
        run: |
          if [ -n "$NEXUS_DEPLOYER" ] && [ -n "$NEXUS_DEPLOYER_PASS" ]; then
            echo "Nexus credentials detected"
            echo "available=true" >> "$GITHUB_OUTPUT"
          else
            echo "Nexus credentials missing, skipping image push"
            echo "available=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          NEXUS_DEPLOYER: ${{ secrets.NEXUS_DEPLOYER }}
          NEXUS_DEPLOYER_PASS: ${{ secrets.NEXUS_DEPLOYER_PASS }}

      - name: Logging into Nexus Container Registry
        if: steps.creds.outputs.available == 'true'
        uses: docker/login-action@v2
        with:
          registry: nexus.kontur.io:8085
          username: ${{ secrets.NEXUS_DEPLOYER }}
          password: ${{ secrets.NEXUS_DEPLOYER_PASS }}

      - name: Extracting Docker metadata
        uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          images: nexus.kontur.io:8085/konturdev/insights-llm-api
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Building and pushing Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: ${{ steps.creds.outputs.available == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Add image tag to step summary
        run: |
          echo "<h3>Docker image tag</h3> $IMAGE_TAG" >> $GITHUB_STEP_SUMMARY
